name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main
jobs:
  entire_workflow:
    name: CI/CD Process
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Run prettier check
      run: npm run format:check
